services:
  postgres-backup:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backups:/backups
      - ./config:/config
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}